server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://database-1.cnaeoekmm64i.ap-southeast-2.rds.amazonaws.com:3306/z_com_bikeride?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: motoride03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect