name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: akshayrajput03
          password: ak$#@yra1!

      - name: Build and push Docker image
        run: |
          docker build -t akshayrajput03/aks-bikeride-com/bikeride .
          docker push akshayrajput03/bikeride
