name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the working directory
        run: ls -la

      - name: Build Docker image
        run: docker build -t akshayrajput03/aks-bikeride-com/bikeride .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u akshayrajput03 --password-stdin
          docker push akshayrajput03/aks-bikeride-com/bikeride
