name: Build Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print working directory and list files
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files:"
        ls -R

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Build Docker image
      run: |
        docker build -t akshayrajput03/aks-bikeride-com/bikeride -f aks-bikeride-com/bikeride/Dockerfile .
